{% set version = "1.2.0" %}
{% set python_min = "3.11" %}

package:
  name: watch-duck
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/w/watch-duck/watch_duck-{{ version }}.tar.gz
  sha256: 7f5a0b50e8997a8d959b81bc5e383d6a195743dc2ad94df75a885a5ac4bfb943

build:
  entry_points:
    - watch-duck = watch_duck.main:cli
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - cfgrib
    - dask-core
    - h5netcdf
    - numpy
    - omegaconf
    - pandas
    - rich
    - rich-click
    - xarray
    - zarr

test:
  imports:
    - watch_duck
  commands:
    - pip check
    - watch-duck --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/watch-duck/
  summary: Python toolbox to track progress of ecflow experiments
  dev_url: https://github.com/aFarchi/watch-duck
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aFarchi
